Storage:
    Type: flatfile
    
    Flatfile:
        Location: ./birthdays.dat
        
    MySQL:
        URL: jdbc:mysql://localhost:3306
        Database: minecraft_server
        Username: root
        Password: lolzzz
        
    Sqlite:
        Location: ./birthdays.sql
       
        
    